version: '3.7'
services:
  web:
    stdin_open: true
    environment:
      - NAMES=true
    image: kartiksj/nodejs:latest  
    restart: always
    # build:
    #    context: .
    #    dockerfile: Dockerfile
    #   image: kartiksj/nodejs:latest
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    image: kartiksj/nodejs:latest  
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']